import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex items-center justify-center min-h-screen min-w-screen
        bg-window-background ">
          <div className=" max-w-20"></div>
          <div className="basis-1/2">
            <div className="flex">
              {children}
              </div>
          </div>
          <div className=" max-w-20"></div>
        </div>

    </body>
    </html>
  );
}
